%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyFilter
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYFILTER_HRL).
-define(OE_COSNOTIFYFILTER_HRL, true).




-endif.


