%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTime
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIME_HRL).
-define(OE_COSTIME_HRL, true).




-endif.


