%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_HRL).
-define(COSNAMING_HRL, true).


-record('CosNaming_NameComponent', {id, kind}).
-record('CosNaming_Binding', {binding_name, binding_type}).


-endif.


