%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming_ext
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_EXT_HRL).
-define(OE_COS_NAMING_EXT_HRL, true).




-endif.


