%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Resource
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RESOURCE_HRL).
-define(COSTRANSACTIONS_RESOURCE_HRL, true).




-endif.


