%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_File
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILE_HRL).
-define(COSFILETRANSFER_FILE_HRL, true).




-endif.


