%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CORBA
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/orber/src/CORBA.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(CORBA_HRL).
-define(CORBA_HRL, true).




-endif.


