%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_SequencePushSupplier
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_SEQUENCEPUSHSUPPLIER_HRL).
-define(COSNOTIFYCOMM_SEQUENCEPUSHSUPPLIER_HRL, true).




-endif.


