%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ChannelIDSeq
%% Source: /net/isildur/ldisk/daily_build/otp_prebuild_r14a.2010-06-15_18/otp_src_R14A/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ChannelIDSeq').
-ic_compiled("4_2_25").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_long,0}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ChannelIDSeq:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ChannelIDSeq".



